language: java
jdk:
- openjdk15
addons:
  sonarcloud:
    organization: cloud-erp-school-system
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cloud-erp-school-system_backendtravis
deploy:
  provider: s3
  access_key_id: AKIA2YWM6KPSHAXMD5TL
  secret_access_key:
    secure: D5MBaGDobKuvGRPh0B6yRw0IfMFqj1NRTdUWXV8qsKXctzwYPL7Vh6ttRqI1eoKc0HB/7qOzBzAWOd7YfU4/K6jImLrpx677X5SlzJZ5BNhzwVktWsBkOu/p/8nzcrm7+NBCS/4pR/JvNgvMhW2fWTmEb3hROVRaXKFpG8qr+r9KaIZqWFBUyWknnkqs+IukcI+NDdbYG2VDVb/Ewde10a5SAgGBabmOwUGa+knoYN1+XLCWe2qaZQeDgelbWGfHM4PczkL/w9YstcHfMMZUVmMATxcxtZULD1+rQrCDNUw7fOKFnqIb8zooIVJgM0872LnvMNi29ZOBLXH/QbMX4qob3WMICx+PQu51+us51HzgM/LAysc9AeIwcy4WyjS8eDkuVLn/MpOb1z9y/a4MPJ1cdT6WnrUXt1hFi/miAhu1PNk9uqCEiWpyHYaDQY8ss86hNXL5R9y1m/MEx59E9KFCcr9C2GZAQd1h4fOgTTdecSKd+Emc0HSu6NFM7bVrAOPpLGntcn2b33zPCHRSS3VLf135UTVvR0Ht8xAndcSH4dIQTC3FjpPaFWiUpxpMuJTCNG772qUkOZafj1ghg8LcYmbjRH7vaMzHKRbyWykE9Qou4E5Xkbji/q5jX5no435aqP06Zh32/ob8mTw+pJ9G4353ALJqxJq/Ra6t2Xw=
  bucket: cloud-erp-school
  acl: private
  on:
    repo: cloud-erp-school-system/backend
    branch: main