version: '3.1'

services:

  database:
    image: mariadb/server:10.4
    restart: always
    container_name: "mariadb"
    ports:
    - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: erp
      MYSQL_USER: erp
      MYSQL_PASSWORD: erp