logging:
  level:
    org:
      atmosphere: warn
server:
  port: 8080
spring:
  datasource:
    password: ''
    url: jdbc:h2:mem:erp
    username: sa
  # Flyway configuration
  flyway:
    check-location: true
    enabled: true
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true
  mustache:
    check-template-location: false
  autoconfigure:
    exclude: org.keycloak.adapters.springboot.KeycloakAutoConfiguration
docs:
  storage:
    directory: /Users/adityasampath/Downloads
# MariaDb configuration
# Initially, let's use H2 for all classes as Flyway will take care of database scripts we don't need to worry now.
#  datasource:
#    password: erp
#    url: jdbc:mariadb://localhost:3306/erp
#    username: erp
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#keycloak:
#  auth-server-url: http://localhost:8180/auth
#  public-client: true
#  realm: master
#  resource: login-app
#  principal-attribute: preffered_username
