name: Google Java Format

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Please, validate if you are using Google Java Format in the code'
        pr-message: 'Please, validate if you are using Google Java Format in the code'
