# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven
      run: mvn clean install -Pproduction
    - name: Qodana - Code Inspection
      uses: JetBrains/qodana-action@v1.0-eap
    - name: Sonar with run Method
      run: >
        mvn --batch-mode
        -Pcoverage
        sonar:sonar
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=cloud-erp-school-system
        -Dsonar.projectKey=cloud-erp-school-system_backend
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        projectKey: cloud-erp-school-system_backend
        orgnization: cloud-erp-school-system
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: /github/workspace/